### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by 12Me21** [LBPHacker/tptasm#6]
`pconf.pathsep, pconf.dirsep, pconf.wildcard = package.config:match("^([^\n]*)\n([^\n]*)\n([^\n]*)\n")` gets `\` as the path separator, but `debug.getinfo(1).source` uses `/` even on windows, so hardcoding it to `/` seems to work.

**Comment by LBPHacker** [comment]
Oops, forgot about this. Ditched that piece of code because modules really didn't work out as well as they tend to, so this is now fixed.

**Comment by LBPHacker** [comment]
I wonder if I broke this again with 5808fd0
